import type { DeviceState } from "../types";

export const typeParsers = {
    number: (v: string): number => Number(v),
    boolean: (v: string): boolean => v === "1" || v.toLowerCase() === "true",
    string: (v: string): string => v,
    object: (v: string): string => v, // Objects should stay stringified!
};

export const deviceStateTypeMap: Record<keyof DeviceState, keyof typeof typeParsers> = {
    BREATHING_LAMP_SWITCH_SET: "boolean",
    DC_OUTPUT_POWER: "number",
    DC_STANDBY_TIME: "number",
    DC_SWITCH_HM: "boolean",
    TEMP: "number",
    MIG_TIME_SWITCH: "boolean",
    MIG_CONNECTION_DATA_HM: "number",
    TOTAL_OUTPUT_POWER: "number",
    DEVICE_SOFT_VER: "string",
    CHARGING_PACK_DATA_JDB: "number",
    HIGH_FREQUENCY_REPORTING: "number",
    USB_SWITCH: "boolean",
    USB_OUTPUT_POWER_HM: "number",
    REMAIN_CHARGING_TIME: "number",
    CURRENCY_UNIT_SET: "number",
    LED_STATUS_HM: "number",
    MEASURE_DATA: "object",
    TIMED_CHARGE_CONNECTION: "object",
    REMAIN_TIME: "number",
    CHARGE_MODE_DATA_HM: "number",
    DEVICE_STANDBY_TIME: "number",
    DEVICETIME: "string",
    BATTERY_PERCENTAGE: "number",
    ECO_MODE_SET: "object",
    SOC_MIG_SWITCH: "boolean",
    DEVICE_ELECTRICITY_USAGE: "number",
    DEVICE_STATUS: "number",
    DC_SOLAR_CURRENT_INPUT: "number",
    SMART_ON_GRID_SWITCH: "boolean",
    SCREEN_BRIGHTNESS: "number",
    TIMED_GRID_CONNECTION: "object",
    CHARGE_MODE_POWER_HM: "number",
    AC_SWITCH_HM: "boolean",
    AUTO_MIG_SET: "object",
    FIT_ELECTRICITY_PRICE_SET: "number",
    AC_OUTPUT_POWER: "number",
    DC_SOLAR_INPUT: "number",
    AC_TIME_SWITCH: "boolean",
    TOTAL_INPUT_POWER: "number",
};
